import { Agent, Workflow } from '../types';

export const SYSTEM_AGENTS: Agent[] = [
  {
    id: 'planner',
    name: 'Planner Agent',
    role: 'Architect & Task Planner',
    description: 'Decomposes complex human requests into structured execution steps',
    avatar: 'Brain',
    status: 'idle',
    color: 'from-amber-500 to-orange-600',
    tools: ['mcp:memory', 'mcp:filesystem'],
  },
  {
    id: 'coding',
    name: 'Coding Agent',
    role: 'Full-Stack Developer',
    description: 'Writes production-grade TypeScript, React, Express, Python & CSS',
    avatar: 'Code2',
    status: 'idle',
    color: 'from-blue-500 to-indigo-600',
    tools: ['mcp:filesystem', 'mcp:terminal', 'mcp:git'],
  },
  {
    id: 'vision',
    name: 'Vision Agent',
    role: 'UI/UX Visual Inspector',
    description: 'Analyzes screenshots, wireframes, charts & visual diagrams',
    avatar: 'Eye',
    status: 'idle',
    color: 'from-emerald-500 to-teal-600',
    tools: ['mcp:playwright', 'inkling_vision'],
  },
  {
    id: 'terminal',
    name: 'Terminal Agent',
    role: 'DevOps & CLI Engineer',
    description: 'Executes npm commands, installs packages, manages processes',
    avatar: 'Terminal',
    status: 'idle',
    color: 'from-purple-500 to-violet-600',
    tools: ['mcp:terminal', 'mcp:git'],
  },
  {
    id: 'browser',
    name: 'Browser Agent',
    role: 'Web Researcher',
    description: 'Browses live web documentation, GitHub repos & StackOverflow',
    avatar: 'Globe',
    status: 'idle',
    color: 'from-cyan-500 to-blue-600',
    tools: ['mcp:browser', 'mcp:playwright'],
  },
  {
    id: 'memory',
    name: 'Memory Agent',
    role: 'Context Retriever',
    description: 'Maintains long-term knowledge base, user facts & project goals',
    avatar: 'Database',
    status: 'idle',
    color: 'from-rose-500 to-pink-600',
    tools: ['mcp:memory', 'mcp:sqlite'],
  },
];

export const SAMPLE_WORKFLOWS: Workflow[] = [
  {
    id: 'build-react-app',
    title: 'Automated Full-Stack React App Setup',
    description: 'Architect, code, run dependencies, start dev server, and open preview',
    trigger: 'User says: Build React App',
    status: 'idle',
    createdAt: Date.now() - 3600000,
    steps: [
      { id: 's1', agentId: 'planner', task: 'Analyze project requirements and generate component architecture', status: 'pending' },
      { id: 's2', agentId: 'coding', task: 'Implement App component, state hooks and Tailwind styles', status: 'pending' },
      { id: 's3', agentId: 'terminal', task: 'Run npm install for required packages', status: 'pending' },
      { id: 's4', agentId: 'terminal', task: 'Start local server on port 3000', status: 'pending' },
      { id: 's5', agentId: 'browser', task: 'Verify live endpoint response and render UI', status: 'pending' },
    ],
  },
  {
    id: 'audit-codebase',
    title: 'Comprehensive Code Audit & Bug Fix',
    description: 'Scan directory tree, detect memory leaks, verify types and refactor',
    trigger: 'User says: Audit Codebase',
    status: 'idle',
    createdAt: Date.now() - 7200000,
    steps: [
      { id: 's1', agentId: 'memory', task: 'Load project history and configuration parameters', status: 'pending' },
      { id: 's2', agentId: 'terminal', task: 'Run TypeScript compiler type check (tsc --noEmit)', status: 'pending' },
      { id: 's3', agentId: 'coding', task: 'Refactor identified syntax errors and dead code', status: 'pending' },
      { id: 's4', agentId: 'vision', task: 'Verify responsive layout contrast and WCAG AA guidelines', status: 'pending' },
    ],
  },
  {
    id: 'deep-research',
    title: 'AI Multi-Source Tech Research',
    description: 'Search documentation, summarize API updates, and build code examples',
    trigger: 'User says: Research Topic',
    status: 'idle',
    createdAt: Date.now() - 10800000,
    steps: [
      { id: 's1', agentId: 'browser', task: 'Fetch latest documentation and API benchmarks', status: 'pending' },
      { id: 's2', agentId: 'planner', task: 'Synthesize research data into structured findings', status: 'pending' },
      { id: 's3', agentId: 'coding', task: 'Generate executable code snippets demonstrating findings', status: 'pending' },
    ],
  },
];
